version: 0.2
phases:
  install:
    commands:
      - echo make venv
      - virtualenv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - echo zappa update dev started on `date`
      - zappa update dev
  post_build:
    commands:
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 0 ]; then zappa rollback dev -n 1; exit 1; fi